pub const LOGICAL_OPERATOR: [&str; 2] = ["AND", "OR"];

pub const COMPARISON_OPERATOR: [&str; 29] = [
    "<",
    ">",
    "<=",
    ">=",
    "=",
    "<>",
    "!=",
    "BETWEEN",
    "NOT BETWEEN",
    "BETWEEN SYMMETRIC",
    "NOT BETWEEN SYMMETRIC",
    "IS DISTINCT FROM",
    "IS NOT DISTINCT FROM",
    "IS",
    "IS NOT",
    "IS NULL",
    "IS NOT NULL",
    "ISNULL",
    "NOTNULL",
    "IS TRUE",
    "IS NOT TRUE",
    "IS FALSE",
    "IS NOT FALSE",
    "IS UNKNOWN",
    "IS NOT UNKNOWN",
    "IN",
    "NOT IN",
    "LIKE",
    "NOT LIKE",
];

pub const ORDER_TYPE: [&str; 2] = ["ASC", "DESC"];
