[package]
name = "hb_api_mqtt"
version = "0.1.0"
edition = "2021"
authors = ["Muhammad Naufal Hilmy Makarim <mail@hilmy.dev>"]


[dependencies]
hb_log = { workspace = true }

anyhow = { workspace = true }
rumqttc = { workspace = true }


[lints]
workspace = true
