[workspace]
resolver = "2"
members = [
    "hyperbase",
    "config",
    "hash/argon2",
    "db/scylladb",
    "dao",
    "mailer",
    "api/rest",
]

[workspace.dependencies]
hb_api_rest = { path = "./api/rest" }
hb_config = { path = "./config" }
hb_dao = { path = "./dao" }
hb_db_scylladb = { path = "./db/scylladb" }
hb_hash_argon2 = { path = "./hash/argon2" }
hb_mailer = { path = "./mailer" }

actix-web = "4"
anyhow = "1"
argon2 = "0.5"
chrono = { version = "0.4", default-features = false }
lettre = { version = "0.10.4", default-features = false, features = [
    "rustls-tls",
    "builder",
    "hostname",
    "smtp-transport",
    "pool",
] }
rand = "0.8"
scylla = "0.10"
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
serde_yaml = "0.9"
strum = { version = "0.25", default-features = false }
tokio = "1"
uuid = { version = "1", default-features = false }
validator = "0.16"
