[package]
name = "dao"
version = "0.1.0"
edition = "2021"

[dependencies]
hb_db_scylladb = { workspace = true }

chrono = { workspace = true }
scylla = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true, features = ["derive"] }
