[package]
name = "dao"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hb_db_scylladb = { path = "../db/scylladb" }
chrono = { version = "0.4", default-features = false }
scylla = "0.10"
uuid = { version = "1", default-features = false }
validator = { version = "0.16", features = ["derive"] }
