[package]
name = "hb_dao"
version = "0.1.0"
edition = "2021"

[dependencies]
hb_db_scylladb = { workspace = true }

anyhow = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
scylla = { workspace = true }
strum = { workspace = true, features = ["std", "derive"] }
uuid = { workspace = true }
validator = { workspace = true, features = ["derive"] }
