[package]
name = "hb_db_scylladb"
version = "0.1.0"
edition = "2021"

[dependencies]
hb_config = { path = "../../config" }
scylla = "0.10"
uuid = { version = "1", default-features = false, features = [
    "v4",
    "fast-rng",
] }
validator = { version = "0.16", features = ["derive"] }
