[package]
name = "hb_db_scylladb"
version = "0.1.0"
edition = "2021"

[dependencies]
hb_config = { path = "../../config" }
hb_db = { path = ".." }
scylla = "0.10"
uuid = { version = "1", features = ["v4", "fast-rng"] }
