[package]
name = "hb_api_rest"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
hb_config = { path = "../../config" }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false }
uuid = { version = "1", default-features = false, features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }
