[package]
name = "hyperbase"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
hb_api_rest = { path = "../api/rest" }
hb_config = { path = "../config" }
hb_db_scylladb = { path = "../db/scylladb" }
tokio = { version = "1", features = ["rt-multi-thread"] }
