[package]
name = "hyperbase"
version = "0.1.0"
edition = "2021"

[dependencies]
hb_api_rest = { workspace = true }
hb_config = { workspace = true }
hb_db_scylladb = { workspace = true }
hb_hash_argon2 = { workspace = true }

futures = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
